### PR TITLE
Switching from pub/sub to sendmail

### PR DESCRIPTION
**Pull request by alexlemaire**
Implemented the following:

- followed the logic from `template-kaskadi-api` using 1 layer that contains all dependencies for this lambda. Also implemented the dependency installation logic that you pushed in `template-kaskadi-api`
- in this layer we have `aws-es-client` and `sendmail` but I also included all helper functions inside of a `utils` folder that I added to the `NODE_PATH` environment variable of my lambda to resolve properly on `require()`
- it works similar to before only that now it fetches from ES all users that are subscribed to the stock report (via `report_stocks` true inside of the `user` document) and dispatches an email to all of them
- instead of being raw text the email body is now HTML (still black & white but a bit better formatting so it's easier to read)

ElasticSearch is already updated with a `user` index which contains all the current employees

### CODE REVIEW

**Comment by Holger-Will** [comment]
`utiles` should go into `/layer/nodejs/node_modules/@kaskadi/utils`...
as i lined out in slack we have to create an exception in `.gitignore` so that everything in `/layer/nodejs/node_modules/@kaskadi/utils` will be tracked by git... no need to mess with NODE_PATH 

(you should really try to avoid using NODE_PATH. i only do that to replicate Lambda instances without us having to install global packages by hand...)

**Comment by Holger-Will** [comment]
it is unlikely that this stayes a single Lambda. Only put things into a layer if they are use by at least two lambdas using that layer. Every module and function used by only one Lambda should stay with that Lambda only...

**Comment by Holger-Will** [comment]
let's just finish the API template and then figure out a rough  layout of what lambdas we need...
for this case here i would rather have a Lambda that gets all Stock Data (probably with params to get different types of stock information...)
Then we would have an Email Lambda that can email a given Body to a list of recipients.
and last we have this Lambda which is run by a cron job and only calls these other two labdas...

**Comment by Holger-Will** [comment]
so, in the end, you can merge your changes but i not think this will stay as it is...

**Comment by alexlemaire** [comment]
> Only put things into a layer if they are used by at least two lambdas using that layer. Every module and function used by only one Lambda should stay with that Lambda only...

Alright layer logic is out now and all utilities are packaged with this lambda. I also added the exception in `template-kaskadi-api` for `layer/nodejs/node_modules/@kaskadi/custom` for potential utilities we want to add for the template as you asked yesterday.

> so, in the end, you can merge your changes but i not think this will stay as it is...

It's fine I think it doesn't need to be in its final state on first shot. We wanted something for Juliane to work with. So if later we modify the backend it's ok if for her everything looks +/- the same

**Pull request merged**
